//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foozie_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD
    {
        public System.Guid food_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string thumbnail { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public System.Guid type_id { get; set; }
    
        public virtual FOOD_TYPE FOOD_TYPE { get; set; }
    }
}
