//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foozie_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public System.Guid order_id { get; set; }
        public System.Guid food_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string note { get; set; }
    
        public virtual FOOD FOOD { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
