//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foozie_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.ORDERs = new HashSet<ORDER>();
        }

        public System.Guid user_id { get; set; }
        public string type { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string first_name { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string last_name { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [RegularExpression(@"^[a-zA-Z0-9.]+@[a-zA-Z]+\.+[a-zA-Z]+" , ErrorMessage = "Email có dạng abc@abc.abc")]
        public string email { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [RegularExpression(@"^0(\d{9})$", ErrorMessage = "Số điện thoại phải là 10 số và bắt đầu từ ký tự 0")]
        public string phone { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string username { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [StringLength(255, ErrorMessage = "Mật khẩu tối thiểu 8 ký tự", MinimumLength = 8)]
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
    }
}
